# Generated by Django 5.1.2 on 2024-11-01 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoggedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.EmailField(
                        error_messages={"unique": "Please enter a valid email id"},
                        max_length=254,
                        unique=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=250,
                        validators=[django.core.validators.MinLengthValidator(8)],
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
